### ISSUE TITLE
itsrdf vs fise properties

### ISSUE THREAD

**Issue by VladimirAlexiev** [NLP2RDF/specification#2]
If you have one NER tool and one annotation (not multiple candidates), NIF says use itsrdf properties.

If you have multiple annotations, you need to use fise properties (the NIF Stanbol profile), as illustrated below.

I think it's a very bad practice to use two completely different property sets for these two situations. Just because in the second case there's an intermediate node for the annotation, doesn't mean the properties should be completely different.

```
</char=0,7> a nif:Word;
  nif:anchorOf "Germany".

# one NER tool, one annotation
</char=0,7>
  itsrdf:taClassRef nerd:Country;
  itsrdf:taIdentRef dbp:Germany;
  itsrdf:taAnnotatorsRef "some tool";
  itsrdf:confidence 0.9.

# multiple annotations: separate node for each
</char=0,7/enrichment=1> a fise:EntityAnnotation;
  fise:extracted-from </char=0,7>;
  fise:entity-type nerd:Country;
  fise:entity-reference dbp:Germany;
  dc:creator "some tool";
  fise:confidence "0.9"^^xsd:float.
```

**Comment by neradis** [comment]
Starting from NIF 2.1, the ITS/FISE dichotomy for entity references will be replaced by the scheme described by (NIF 2.1 Provenance and Confidence)[http://nif.readthedocs.org/en/2.1-rc/prov-and-conf.html], thus ITSRDF properties will also be used in situations the multiple alternative entities/ entity candidates.
